---
title: "HR Analytics: An exploratory plot of why Employees Left The company"
runtime: shiny
output: html_notebook
---
```{r,include=FALSE,cache=TRUE}
source("library.R")
```

```{r,include=FALSE,cache=TRUE}
# Use the Human Resources data set.
d <- read_csv(file.path("data","HR_comma_sep.csv"))
d <- d %>% mutate(left_f = factor(left,levels=c(0,1),labels=c('No','Yes')))
label(d$left_f) <- "Left Company"
```

Here is what the data set looks like.
```{r,warning=FALSE,echo=FALSE}
DT::renderDataTable(d,width=6)
```

Look at the class of each field.
```{r,echo=FALSE}
renderPrint(sapply(d,"class"))
```

## Density Plot
Choose what field to plot.
```{r,include=TRUE,echo=FALSE}
selectInput("var_x","X axis:",choices = names(d),selected = "satisfaction_level")
```

Create density plot of the chosen field.
```{r,echo=FALSE}
renderPlot({ 
  d %>% ggplot(aes_string(x=input$var_x,fill="left_f")) + 
    geom_density(alpha=0.4)  +
    labs(title = "Why Did Employees Leave the Company?",fill="Left Company")
  }) 
```

```{r,include=FALSE}
  d %>% ggplot(aes(x=Work_accident,fill=left_f)) + 
    geom_density(alpha=0.4)  +
    labs(title = "Why Did Employees Leave the Company?")
```








